version: "3.3"

services:
  frontend:
    build: ../web-app-kidsartceaft-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ../web-app-kidsartcraft-backend
    # ports:
    #   - "5000:5000"
    env_file:
      - ../web-app-kidsartcraft-backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ../web-app-kidsartcraft-backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
